#encoding updated as per https://gist.github.com/amolkhanorkar/8706915

development:
  adapter: postgresql
  encoding: utf8
  database: CodeMonkeys_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: CodeMonkeys_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: CodeMonkeys_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST